### PR TITLE
Fix: don't print the menu wrapper when no menu set

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Should fix:
http://themesandco.com/support-forums/topic/adjusting-size-or-removing-empty-navbar/
http://themesandco.com/support-forums/topic/disable-3-bar-menu-on-single-page-site/

### CODE REVIEW

**Comment by Nikeo** [comment]
Hi Rocco,
What is a menu not set ? is it when no menu has been assigned to the main location of the theme ?
In this case, id you check that the fallback is still fired ?
'fallback_cb'     => array( $this , 'tc_link_to_menu_editor' )

Thanks

**Comment by eri-trabiccolo** [comment]
A menu not set is .. yes when you don't set the menu to the main location of the theme.
And when the fallback is fired "there is a menu", that happens when user's logged in and can manage themes right? So in that case the wrapper is still printed.
Is not printed when you haven't set a menu to the main location of the theme, and when that fallback doesn't return anything.
I'll make another test anyway.

**Comment by eri-trabiccolo** [comment]
This pr is wrong, I'm investigating on the causes :D

**Comment by eri-trabiccolo** [comment]
Ah the problem is caused by the old tc_navbar_display do we want to finally get rid of it and make tc_new_menu_view be the real tc_navbar_display?

**Comment by Nikeo** [comment]
ah ok. 
getting rid of the old navbar_display : I don't have a clear idea of the possible consequences and don't have the time to investigate now. Let's postpone this PR then.

**Comment by eri-trabiccolo** [comment]
Ah no, was me doing a wrong test.
I update this pr

**Comment by eri-trabiccolo** [comment]
Done,
but yes feel free to postpone it ;)

**Comment by eri-trabiccolo** [comment]
Close this messy pr. :D

**Pull request closed without merging**
