### PR TITLE
Fix: fix old customizer logo not shown in live preview even if not ov…

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
…erridden

see https://github.com/presscustomizr/customizr/issues/1633#issuecomment-447592721

### CODE REVIEW

**Comment by ghost** [comment]
thanks for the fix !

**Comment by ghost** [comment]
I'm waiting for the fix https://github.com/presscustomizr/customizr/issues/1642  to release it

**Comment by eri-trabiccolo** [comment]
Ah!
Ok will accelerate making it simple (meaning that I will barely copy the 2019 one) then: the thing is that I'm not very convinced about that, mostly because of possible plugins conflicts - which one? I don't know, but I know that they can occur because the block editor html/CSS is not done in a way that just changing a param (say the content width) everything will be scaled accordingly.

**Comment by ghost** [comment]
OK let's do like that.
I propose that we postpone the 14:30 chat until you have finished a first prototype that we can discuss. Fine for you ?
( no problem if this is tomorrow ! )

**Pull request merged**
