### PR TITLE
Fix: avoid plugin's conflicts with the centering slides feature:

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
replace the #customizr-slider's 'slide' class with 'customizr-slide'

Alternatively we can parametrize it (tcparams)
or yell at some developers :P

### CODE REVIEW

**Comment by Nikeo** [comment]
Hi Rocco!
Thanks for this. Since the slider is a pretty sensitive thing I really want to be extremely cautious on this one, so :
1) Did you make sure that there's no side effect with this class changes, server side + browser side ?
2) Can you confirm that this has been tested with a previously cleaned browser cache ?

Thanks !

**Comment by eri-trabiccolo** [comment]
Hi Nico, well 
2) should confirm 1) right? Unless I didn't miss anything.
Yes I tested it, mainly because I wasn't sure that just those 2 changes will be enough. :)
I'll test it again.

**Comment by Nikeo** [comment]
OK thanks. I've made some tests too and everything looks good.
Merged

**Comment by eri-trabiccolo** [comment]
:+1:

**Pull request merged**
