### PR TITLE
Fix: avoid Chrome visible line issue by removing the perspective rule…

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
… where not necessary

see https://github.com/presscustomizr/tc-unlimited-featured-pages/issues/133

### CODE REVIEW

**Comment by ghost** [comment]
related ? https://wordpress.org/support/topic/featured-image-are-surrounded-by-a-line/

**Comment by eri-trabiccolo** [comment]
Yes totally related. Also the guy with the custom CSS is the pro user who reported it in the first place.

**Comment by ghost** [comment]
unbelievable number of years we needed to work on this, and commits, to polish this feature / effect !

**Comment by eri-trabiccolo** [comment]
yes, but I think this latest issue has been introduced recently by chrome...

**Pull request merged**
