### PR TITLE
Fix: disable link smoothscroll in woocommerce contexts

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
See issue #258

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Otherwise, we should implement an "exclude selectors" which isn't based only on the link CSS class but also on the parents classes/id, exactly as we do with the external links.
https://github.com/Nikeo/customizr/blob/master/inc/assets/js/parts/jqueryextLinks.js#L73

this method could be ported in czrapp constituting an utility.
What do you think?

**Comment by Nikeo** [comment]
yep agreed 100% !

**Comment by eri-trabiccolo** [comment]
Perfect, will do that at my return ;)

**Comment by eri-trabiccolo** [comment]
so you chose this one?

**Pull request merged**
