### PR TITLE
Fix: expand last published sticky post in the grid

### LINKED ISSUE #277: Grid expanded post
At the moment the expanded sticky post is not the latest published but just the first in the array of the sticky_posts option. We should retrieve the latest published among those posts.A custom SQL should be the less expensive way.

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Fixes #277

### CODE REVIEW

**Comment by Nikeo** [comment]
merged in dev

**Comment by eri-trabiccolo** [comment]
Anyway I missed this comment:

> Now it also set the "expanded_sticky" property.

it already did that (I remember that at a certain point we introduced that), the only difference is that now it does it better.

**Comment by eri-trabiccolo** [comment]
Here's where we (I) introduced the caching:
https://github.com/Nikeo/customizr/commit/506e9449587b2e2bc9a76a292f0459603503d413

**Comment by eri-trabiccolo** [comment]
Actually this PR misses a condition in the query:
AND post_status = 'publish'

I'll propose a PR to fix this + new function to cache the sticky post, in a few hours (lunch time here ;))

**Pull request closed without merging**
