### PR TITLE
Emoji

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Should work fine.
Needs your check though.

With this code  we also load the holder.js only when needed.

### CODE REVIEW

**Comment by Nikeo** [comment]
you've already moved modernizr in the head !! :)

**Comment by eri-trabiccolo** [comment]
Sorry, this is a typo ... too many branches here :D 
You better move it to the footer again... :/

**Comment by Nikeo** [comment]
ah
mmm is it the only one? or could there be others :/

**Comment by eri-trabiccolo** [comment]
The only one typo coming from another branch yep.
But about the classic plugin we relies on that plugin's code, I've tested that the old emoj work fine and that the new emoj are used instead, when you don't want to display fp images and so on.
I've changed the plugins code in order to not affect "admin" part also.
That's basically 'cause I use some TC_featured_pages helpers which as you know are unavailable when is_admin. ...

**Comment by Nikeo** [comment]
ok looks perfect. thanks :)

**Comment by eri-trabiccolo** [comment]
:)

**Pull request merged**
