### PR TITLE
Fix: some minor changes to avoid weird behavior when loading page

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
and sticky header set, also fix logos dimension not set (_.isNumber(num) returned false on width and height attr values => pretty important! )

on page loading:
a) CSS: set top: 0 when sticky disabled in CSS, it will changed in js if needed (see admin bar)
b) CSS: make tc-margin-top always visible for tc-sticky-header body class, this will reduce the jumping of the content while loading the page (before js takes effect)
c) JS: in LOADING ACTIONS call also  _scrolling_actions(). This because sometimes when you refresh (browser) an already scrolled page (or go to an anchor in a different page), for some reason (at least with chrome) the scroll event isn't fired => the header stays with its original size.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
With the last commit we should avoid side effects if any. Since when sticky header enabled the body has "sticky-disabled":
1) if $(window).scrollTop() > triggerHeight => add sticky-enabled class and remove sticky-disabled class => fine, that's what we want in those case when browsers doesn't fire the scroll event when loading the page
2) otherwise since body hasn't the class sticky-enabled, nothing will happen => fine

**Comment by eri-trabiccolo** [comment]
which part? just the css part I hope, right?

**Comment by Nikeo** [comment]
js part but no worries, it should be fine

**Comment by eri-trabiccolo** [comment]
Mmm, but the js part was already in the core code ... the only missing part of this pr should have been the css part .. mmm

**Pull request merged**
