### PR TITLE
Updated translations for v 3.3.19 and first pre-phase of RTL-ing

### PR DESCRIPTION
**Pull request by JTS-IL**

### CODE REVIEW

**Comment by JTS-IL** [comment]
This pull request includes all Hebrew translations for all untranslated phrases updated to v 3.3.19

**Comment by JTS-IL** [comment]
Two updates:
1. RTL-ing Pre-Phase : setting the correct direction of arrows (class-content-post-navigation,php)
    added to variables that hold the correct "arrow" according to direction (RTL/LTR) of site
2. Correcting arrows on few Hebrew trasnlated phrases

**Comment by Nikeo** [comment]
Looks perfect, Thanks Yaacov :+1:)

Merged in the dev branch.
I'll do some testing but it should be included without changes.
Thanks for your contribution

**Comment by JTS-IL** [comment]
:-)
The next phase of RTL will be uploaded soon

**Pull request closed without merging**
