### PR TITLE
Fix: display unknown archive types headings;

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
use if/else statement when retrieving archive headings/classes
immediatily return the archive class when asked for and achive matched

for something reported here:
http://wordpress.org/support/theme/customizr

### CODE REVIEW

**Comment by Nikeo** [comment]
OK
Did you managed to check this with all archive cases ?
What was the initial problem to treat if you can remember it? (I can't find the related topic...)
thanks Rocco

**Comment by eri-trabiccolo** [comment]
I checked that with all the archive type cases I could think about :D so tags authors and so on.
Well I pasted a very useful link for that topic ahah, sorry.. was this -> https://wordpress.org/support/topic/taxonomy-archive-how-to-display-title-and-description#post-6855755

That's a typical case.
Consider that I looked at the twentyfifteen archive.php to see why they worked fine :D .. So if it's an archive and isn't one of them we take care of just "fallback" on the common way to display them. That's the sense.
What do you think?

**Comment by Nikeo** [comment]
ok. looks good !
merged in dev

**Comment by eri-trabiccolo** [comment]
what's that dancing emoticon? well think about I used it :P

**Pull request closed without merging**
