### PR TITLE
Translated few strings in Italian.

### PR DESCRIPTION
**Pull request by giorgioriccardi**
Some strings about the grid system have been left for Rocco

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Yep :D Thanks, feel free to change strings you thing should be translated better ;) and can you correct this "piccolo porzioni" (from your last commit)?
:D

**Comment by giorgioriccardi** [comment]
Here it is, can be improved of course... but not today!

**Comment by eri-trabiccolo** [comment]
:D Thanks Giorgio

**Comment by giorgioriccardi** [comment]
I will keep updating the Italian version anytime I'll spot a typo... problem is that I rarely use it in Italian... review to be continued

**Comment by Nikeo** [comment]
Merged in dev. Thanks for this contribution Giorgio ! :D

**Pull request closed without merging**
