### PR TITLE
Italian Translation improved

### PR DESCRIPTION
**Pull request by giorgioriccardi**
Improved a little bit the Italian Translation and few tweaking on the English text [nothing major though]

### CODE REVIEW

**Comment by giorgioriccardi** [comment]
Hi Rocco and Nicholas,
I'm pushing few changes in the Italian text (Rocco, there were again dirty chars from your last translation - dunno why!) and I also changed few empty spaces in some core files.
It is nothing major or important, just polishing few details, so not a big deal if they won't merged.

On another line I was trying to translate the new text for the latest version of Customizr, for example the admin comments in the header:
"You can now display your menu as a vertical and mobile friendly side menu, animated when revealed.
Try it with the demo or change your menu design now."
But I can't find it anywhere; am I missing something here?

Let me know,
happy to keep up with the translation.

**Comment by eri-trabiccolo** [comment]
Hello Giorgio,
dirty chars from my latest translation? Weird.
Thanks. :+1: 
About the sentence you couldn't find, the thing is that po files have not been updated. You probably should reload the catalog to refresh the strings to translate.

**Comment by giorgioriccardi** [comment]
Thanks Rocco,
I'm not very skilled with Poedit, I will proceed with a first translation and maybe you wanna double check later or whenever.
Ciao

**Comment by eri-trabiccolo** [comment]
Fine for me :D 
Ciao

**Pull request closed without merging**
