### PR TITLE
Fix: don't display the menus when no menu is set

### PR DESCRIPTION
**Pull request by eri-trabiccolo**

### CODE REVIEW

**Comment by Nikeo** [comment]
Hi Rocco, could you quickly recall me what problem does this PR solve ?
Thanks (sorry you've been pushing this one a while ago :) )

**Comment by eri-trabiccolo** [comment]
This was born a while ago to solve a minor issue, which is the printing of the resp menu button even if no menu is set.
Here an example of filed bug:
http://presscustomizr.com/support-forums/topic/disable-3-bar-menu-on-single-page-site/

**Comment by Nikeo** [comment]
ah ok. Thanks.

**Comment by eri-trabiccolo** [comment]
Yeah not very important stuff :)

**Comment by Nikeo** [comment]
yep :D. but thanks for the quick reply anyway

**Comment by eri-trabiccolo** [comment]
you're welcome, until the memory will allow me to remember medium-recent events :D

**Comment by eri-trabiccolo** [comment]
Included in the menu revamp

**Pull request closed without merging**
