### PR TITLE
Add: add new body class for the current layout

### PR DESCRIPTION
**Pull request by eri-trabiccolo**

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Feel free to trash it if you don't like the "idea".

**Comment by Nikeo** [comment]
Why not but do you have an example of use case / situation when this particular layout class is missing ?

**Comment by eri-trabiccolo** [comment]
I thought at it here -> http://themesandco.com/support-forums/topic/sidebar-widget-not-resizing-on-tablet/#post-50527

In this case I proposed to but left and right borders to the #content but it's right when you use both sidebars, so I thought that in general having a css class for the current layout would have been useful

**Comment by Nikeo** [comment]
OK got the point thanks

**Comment by Nikeo** [comment]
added in dev

**Pull request closed without merging**
