### PR TITLE
Fix: modern - fix Terms and Condition checkbox in Checkout page is not

### LINKED ISSUE #1340: WooCommerce: Terms and Condition checkbox in Checkout page is not really visible
reported here on HelpScout, but the user is running the Customizr (non Pro) theme: 
https://secure.helpscout.net/conversation/491171725/35742?folderId=607541)

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
really visible

fixes #1340

### CODE REVIEW

**Comment by ghost** [comment]
that was fast

**Comment by eri-trabiccolo** [comment]
That's a trick, I wrote the issue when I had the solution :P

**Comment by ghost** [comment]
ah I see  :)
but kinda scaring...how many unsolved issues have never been opened then ? 🤐

**Comment by eri-trabiccolo** [comment]
ahah I always solve them! :P 
Nope, it depends, when I see it's important I try to find a solution before writing the issue - and if I don't find it in a reasonable time i write the issue anyways-, otherwise I only write the issue.

**Comment by ghost** [comment]
I knew it. You always find a solution.
The good thing with us developers, is that we define what is a "reasonable time" !  ( I totally include myself ). :D

**Pull request merged**
