### PR TITLE
Fix: modern - fix displaying related posts in pages

### LINKED ISSUE #1713: Related post not disabled despite selecting the "disabled" option
https://secure.helpscout.net/conversation/808034735/216686?folderId=607547
@eri-trabiccolo when you'll have the time, can you let me know if this is something you can reproduce.
I'm not able to reproduce it for the moment.

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
when The Events Calendar plugin is active.
fixes #1713

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
I did a fantastic plugin compatibility job recently: kudos!

**Comment by ghost** [comment]
I'm having lot of fun building releases .... :)
giphy

**Comment by eri-trabiccolo** [comment]
Ahah, well you know how that scene is going to end up Dude...

**Comment by ghost** [comment]
yeah I know :)

**Pull request merged**
