### PR TITLE
Fix: fix post-navigation regression introduced while merging rtl code

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
This regression forced the hiding of the psot-navigation in pages (we have an option now) and the showing in any other context, overriding the filtered boolean state (see post-navigation shown in bbpress).

### CODE REVIEW

**Comment by JTS-IL** [comment]
Can you please explain why/how it is related to the RTL fix?

**Comment by eri-trabiccolo** [comment]
Not your fault JTS :),
it's something happened while merging different branches, some old parts of the code, have been reintroduced :D
https://github.com/Nikeo/customizr/commit/8cb545fa98b6c86e77904c5a8ffb24d2a8cd1f23#diff-d4b63356cdfb97d3a0f2146553a0264aR73

**Comment by Nikeo** [comment]
Hi Yaacov, my fault : I did not correctly merged your pull request !

**Comment by JTS-IL** [comment]
I thought that it had to do with wrong forking of the main repository that I did :-)

**Pull request merged**
