### PR TITLE
Add: new filter tc_post_list_controller

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Useful for cpt list templates.
See: https://wordpress.org/support/topic/custom-pages-template-andor-custom-loops-in-conflict-with-customizr-pro?replies=4#post-6578043

### CODE REVIEW

**Comment by giorgioriccardi** [comment]
glad that bugging you guys, leads to improvements ;-)

**Comment by Nikeo** [comment]
added in dev. Thanks Rocco !

**Comment by eri-trabiccolo** [comment]
"Unless I see the nail marks in his hands and put my finger where the nails were, and put my hand into his side, I will not believe."
John 20:25

**Comment by Nikeo** [comment]
ah ah ah, you quoting the bible ! :)

**Comment by eri-trabiccolo** [comment]
Ahhh that was from the bible? :P

**Comment by eri-trabiccolo** [comment]
It's an unequal struggle :P

**Pull request closed without merging**
