### PR TITLE
Imp: handle .tc-no-title-logo, when sticky enabled, in css

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Tested, but you better test it too :P

### CODE REVIEW

**Comment by Nikeo** [comment]
Hi Rocco, can you recall me what is the problem solved here? Is it the issue reported for a big logo ?

**Comment by eri-trabiccolo** [comment]
Nope.. Is the issue about that little flashing an user on the pro support () reported. Basically there's a little range in which sticky is enabled but navbar-wrapper is still span9. Then scrolling up it become 12 and then 9 again. This fixes the issue and is also very simple.

**Comment by eri-trabiccolo** [comment]
Ah, also, using span9, statically, isn't very safe, I think, since through filters, you can change that value, so if you still want to use the js method (I disagree, but it's your theme :P) you should pass it in TCParams, like you do with the sidebars...
Though it will still work when you use spanX with X < 9, since, in the css, they come after 9, so span9 css is overridden, but if a user changes the navbar-wrapper class to span10, then it's wrong..

**Comment by Nikeo** [comment]
I am convinced by your CSS solution.
To be merged ! thanks

Issues : yes I will!

**Comment by Nikeo** [comment]
merged in dev

**Comment by Nikeo** [comment]
About issues : I don't think there are github issues to adress ?
Are you mentioning the forum issues on niclook ?

**Comment by eri-trabiccolo** [comment]
Nope, I use niclookbug for those :P 
I use nicklook to inform you of good things, or to let you know how greatly I handled a certain situation :P 
Eheh
I meant the extensions' issues (wfc/fpu).
About customizr issues, the missing script is solved right? So I can close the last two I opened

**Comment by Nikeo** [comment]
ah ah!
OK yes the wfc/fpu.
Yes missing script solved.

I'm done for today ! good evening Rocco.

**Comment by eri-trabiccolo** [comment]
Good evening too :)

**Comment by eri-trabiccolo** [comment]
You're served, now there's a new entry in niclookbug :P

**Pull request closed without merging**
