### PR TITLE
Fix: better check on when changing default slider's height

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Reported by @daymobrew
Slightly different version of his proposed patch.
ref: https://wordpress.org/support/topic/notice-undefined-index-tc_slider_default_height

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Don't you want include this one in the next release?

**Comment by Nikeo** [comment]
mmm you're right, I'll include it in v3.3.0.

**Comment by eri-trabiccolo** [comment]
Ok, probably nobody will notice it ;)

**Comment by damiencarbery** [comment]
No need for me to submit my patch as this one is better. Thanks for fixing.

**Pull request merged**
