### PR TITLE
Main blocks flex reorder

### PR DESCRIPTION
**Pull request by eri-trabiccolo**

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Basically consists in : 
1) wrap elements like comments, related posts, author info in a single element
2) "write" this element just after the article-container -> defines the position in "mobiles" (<768px)
3) assign to this element the order-md-last CSS class that pushes it after the sidebars in medium devices viewports (md min-width is 768px)

**Comment by ghost** [comment]
Can I safely push live ?

**Comment by ghost** [comment]
or shall I wait tomorrow
(I'm about to push a new release for this bug : https://github.com/presscustomizr/customizr/commit/c453e206f83cf1b80d0c6c2be3f05387b0f65e5b

**Comment by eri-trabiccolo** [comment]
Ops sorry,
yeah tested.

Looking at your bug now.

**Comment by eri-trabiccolo** [comment]
Ah yeah I see the bug, stupid and urgent. :(

**Comment by ghost** [comment]
I fixed it
simply style.css hardcoded.

**Comment by ghost** [comment]
yeah stupid ! my fault

**Comment by eri-trabiccolo** [comment]
Mmm, well I think it's my fault, I wrote that, no?!

**Comment by ghost** [comment]
yeah but I changed it ( we were together ) afterwards.
anyway. I consider it's your fault. You know that.

:)

**Pull request merged**
