### PR TITLE
Fix: CenterImages js avoid using ir8 reserved words

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Looks like "class" is a reserved word for ie8..!?
More info here: https://wordpress.org/support/topic/expected-identifier-line-3-char-5937-tc-scriptsminjsver339?replies=5#post-6696463
we'll see what JTS_IL will answer.

### CODE REVIEW

**Comment by Nikeo** [comment]
fixed in dev

**Comment by eri-trabiccolo** [comment]
Mmm, not the "stray commas" part ;)
still there

**Comment by Nikeo** [comment]
done => was it generating errors ?

**Comment by eri-trabiccolo** [comment]
Well, haven't tested since I couldn't find a ie8 :D But accordingly with what that guy said looks like it did..

**Pull request closed without merging**
