### PR TITLE
Fix: modern - improve nav__utils alignment

### PR DESCRIPTION
**Pull request by eri-trabiccolo**

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Please include this too :/

**Review by ghost — APPROVED** [review]
OK. was this related to an issue reported somewhere ?

**Comment by eri-trabiccolo** [comment]
Nope, just noticed and wanted to make it fast ;)

**Comment by eri-trabiccolo** [comment]
You can see the issue this PR fixes in the current demo:


the menu button should be aligned to the blue line.

**Pull request merged**
